### ISSUE TITLE
Pin test button doesn't render

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/vscode-go-autotest#49]
![bfd4c434-dbf4-4452-ba1e-3f944efb0e2d](https://user-images.githubusercontent.com/452453/40798030-0852a0ce-64d8-11e8-997f-28dd06e4fff0.jpg)

Here's what's in the console:

```
[windmilleng.vscode-go-autotest]Cannot read property 'fileName' of undefined
e.$onExtensionRuntimeError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2915
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2915 TypeError: Cannot read property 'fileName' of undefined
	at updatePinnedTestLocation (/Users/cha/.vscode/extensions/windmilleng.vscode-go-autotest-1.5.0/out/src/goTest.js:268:26)
	at invokeFunc (/Users/cha/.vscode/extensions/windmilleng.vscode-go-autotest-1.5.0/node_modules/lodash/lodash.js:10333:23)
	at trailingEdge (/Users/cha/.vscode/extensions/windmilleng.vscode-go-autotest-1.5.0/node_modules/lodash/lodash.js:10382:18)
	at Timeout.timerExpired [as _onTimeout] (/Users/cha/.vscode/extensions/windmilleng.vscode-go-autotest-1.5.0/node_modules/lodash/lodash.js:10370:18)
	at ontimeout (timers.js:386:14)
	at tryOnTimeout (timers.js:250:5)
	at Timer.listOnTimeout (timers.js:214:5)
e.$onExtensionRuntimeError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2915
```

Happened when looking at this file https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks_test.go

Reported by @chuckha 💚

**Comment by chuckha** [comment]
![screen shot 2018-05-31 at 5 25 10 pm](https://user-images.githubusercontent.com/98927/40809197-99de0168-64f7-11e8-8887-a9a840f35ef1.png)

y'all rock! thx
