### ISSUE TITLE
Plugin crash

### ISSUE THREAD

**Issue by chuckha** [windmilleng/vscode-go-autotest#53]
This plugin crashed looking at this file:

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/config/masterconfig_test.go

and adding a new test that looks approximately like this:

```
func TestSetInitDynamicDefaults(t *testing.T) {
	cfg := &kubeadm.MasterConfiguration{}
	if err := SetInitDynamicDefaults(cfg); err != nil {
		t.Fatalf("failed to set init dynamic defaults: %v", err)
	}
}
```

Here is the stacktrace I discovered.

```
[windmilleng.vscode-go-autotest]Channel has been closed
e.$onExtensionRuntimeError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2915
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2915 Error: Channel has been closed
	at e.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:554:591)
	at e.appendLine (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:554:225)
	at testResultLines.forEach.line (/Users/cha/.vscode/extensions/windmilleng.vscode-go-autotest-1.6.0/out/src/testUtils.js:137:67)
	at Array.forEach (native)
	at processTestResultLine (/Users/cha/.vscode/extensions/windmilleng.vscode-go-autotest-1.6.0/out/src/testUtils.js:137:37)
	at outBuf.onDone.last (/Users/cha/.vscode/extensions/windmilleng.vscode-go-autotest-1.6.0/out/src/testUtils.js:149:21)
	at lastListeners.forEach.listener (/Users/cha/.vscode/extensions/windmilleng.vscode-go-autotest-1.6.0/out/src/util.js:383:48)
	at Array.forEach (native)
	at LineBuffer.fireDone (/Users/cha/.vscode/extensions/windmilleng.vscode-go-autotest-1.6.0/out/src/util.js:383:28)
	at LineBuffer.done (/Users/cha/.vscode/extensions/windmilleng.vscode-go-autotest-1.6.0/out/src/util.js:377:14)
	at ChildProcess.proc.on.code (/Users/cha/.vscode/extensions/windmilleng.vscode-go-autotest-1.6.0/out/src/testUtils.js:161:24)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at maybeClose (internal/child_process.js:899:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
e.$onExtensionRuntimeError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2915```

**Comment by chuckha** [comment]
restarting vscode seems to have fixed it

**Comment by MaerF0x0** [comment]
@windmilleng you can probably close this ^^
